require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.7
  Exclude:
    - 'client/*'
    - 'db/migrate/*'
    - 'db/schema.rb'

  NewCops: enable

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/PreferredHashMethods:
  EnforcedStyle: verbose

Layout/LineLength:
  Max: 100

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*_spec.rb'
    - 'lib/tasks/*.rake'
    - 'config/routes.rb'
    - 'config/deploy.rb'

Rails/SkipsModelValidations:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/NestedGroups:
  Max: 6
